% Chocolate labelling GUI for MTRN4230.
%
% Sam Marden 2014.
% Steven Zheng 2015.
% Julie Tang 2017.

function handles = add_rectangle(handles, mouse_location)

    handles.userdata.rectangles = [handles.userdata.rectangles; ...
    [mouse_location, ...
    0, ...
    handles.userdata.rectangle_colour, ...
    handles.userdata.rectangle_shape,	...
    handles.userdata.rectangle_uppersurface, ...
    handles.userdata.rectangle_reachable, ...
    ]];

handles.userdata.rectangle_idx = size(handles.userdata.rectangles, 1);
